---
- name: Create necessary folders
  file:
    dest: "{{ item }}"
    owner: "{{ flask_server_user }}"
    group: "{{ flask_server_group }}"
    mode: 0755
    state: directory
  sudo: yes
  with_items:
    - "{{ flask_repo_path }}"

- name: Install dependencies
  apt:
    name="{{ item }}"
    state=present
  with_items:
    - python-pip
    - python-virtualenv
    - git
  sudo: yes

- name: Install Flask and Gunicorn
  pip:
    name="{{ item }}"
    state=present
  with_items:
    - Flask
    - gunicorn
  sudo: yes

- name: Clone flask app
  git:
    repo="{{ flask_repo }}"
    dest="{{ flask_repo_path }}/{{ flask_app_name }}"
    key_file="{{ flask_git_priv_key_path }}"
    accept_hostkey=yes
  sudo: yes
  sudo_user: "{{ flask_server_user }}"

- name: Run Flask app
  shell: 'nohup gunicorn -w "{{ flask_workers }}" -b "{{ flask_host }}:{{ flask_port }}" "{{ flask_app_name }}":app > /tmp/flask.log 2>&1 &'
  args:
    chdir: "{{ flask_repo_path }}/{{ flask_app_name }}"
  sudo: yes
  sudo_user: "{{ flask_server_user }}"
